# Generated by Django 3.2.6 on 2021-09-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(choices=[('general_query', 'GENERAL QUERY'), ('where_is_my_order', 'WHERE IS MY ORDER?'), ('complaint', 'COMPLAINT'), ('collaboration', 'COLLABORATION')], default='general_query', max_length=100)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Query',
            },
        ),
    ]
